#!/bin/bash
# pull luajit sources
cd "$(dirname "$0")" || exit 1

getupdate() {
	([ ! -d $1 ] && git clone https://github.com/LuaJIT/LuaJIT.git $1
	cd $1 || return
	git checkout $2
	git pull origin $2
	)
}

getupdate luajit-2.1 v2.1
getupdate luajit-2.0 master
