#!/bin/bash

cd "$(dirname "$0")" || exit 1

if [ ! -d luajit ]; then
    git clone git@github.com:capr/luajit.git
    cd luajit || exit 1
    git remote add upstream http://luajit.org/git/luajit-2.0.git
else
    cd luajit || exit 1
fi

git checkout master
git pull upstream master
git push origin
git checkout v2.1
git pull upstream v2.1
git push origin
