#!/bin/bash
# rebuild all htags

rootdir=$(dirname "$0")
cd $rootdir || exit 1
rootdir=$PWD

mktags() {
    (cd $2 || return
    local gdir=$rootdir/$1.gtags
    local hdir=$rootdir/$1.htags
    mkdir -p $gdir
    mkdir -p $hdir
    gtags $gdir
    rm -f $hdir/HTML/style.css
    htags -anoTx -t $3 --insert-header $rootdir/header.html -d $gdir $hdir
    ln -sf $rootdir/style.css $hdir/HTML/style.css
    )
}

mktags luajit-2.1 luajit-2.1/src     luajit
mktags luajit-2.0 luajit-2.0/src     luajit-2.0
mktags dynasm     luajit-2.1/dynasm  dynasm
